### ISSUE TITLE
Does not work in M$ environment

### ISSUE THREAD

**Issue by riker09** [0xFireball/YetAnotherShrinker#1]
I got your demo app working just fine under Ubuntu 16.04 using Visual Studio Code. Well, I ran into a few startup headaches but they were all caused by me, so everything is fine here.

However, when I tried launching my app in Visual Studio 2015 I ran into errors. At first, I thought it was something I did (again), but I just cloned your repo, restored packages and project files, hit the Debug button and voilá:

![vue-error](https://cloud.githubusercontent.com/assets/568497/22501978/55cd62de-e86b-11e6-87b6-a77f6a11d085.png)

Same error I'm getting with my customized app. I'm an absolute beginner regarding VS2015, Vue and Webpack, so I have no clue where to start looking and I would be greatful for some insights.

**Comment by 0xFireball** [comment]
Hello,

Try switching the Run configuration from IIS Express to just launch the project executable instead.

**Comment by riker09** [comment]
I'm not sure if I understood your instructions. But I edited the solutions properties, created a new Debug profile with the option `Lauch` set to `Project`. I also supplied the working directory (`\Folder\To\Project\YetAnotherShrinker\src\YetAnotherShrinker`) and a launch URL (`http://localhost:5000/`). I also added a single ENV var: `ASPNETCORE_ENVIRONMENT` => `Development`

This is the error from the Chrome web inspector:

![yas](https://cloud.githubusercontent.com/assets/568497/22541700/3ba54440-e928-11e6-8d84-1901764c0f51.png)

I'm suspecting there is something wrong with the way webpack handles files on Windows. To get the project starting at all I had to edit the build/utils.js file slightly:

```diff
    ? config.build.assetsSubDirectory
    : config.dev.assetsSubDirectory
-  return path.posix.join(assetsSubDirectory, _path)
+  return path.join(assetsSubDirectory, _path)
}

```

**Comment by 0xFireball** [comment]
@riker09 yes, that's exactly what I meant.

That's very odd because I developed the app in Visual Studio. I'll have a look for you later today.

**Comment by riker09** [comment]
@0xFireball Out of curiosity: Did you ever find the time to look into this?

**Comment by 0xFireball** [comment]
I'm not sure what's wrong. It works without any problems on my computer?

**Comment by riker09** [comment]
Thanks for your help. If I ever find out what's wrong I'll let you know here.

**Comment by 0xFireball** [comment]
Sorry about not being able to help you, but I have no idea what's wrong. I don't know that much about Webpack, maybe you should ask those guys.
