### ISSUE TITLE
Hot replacement not working in IE 11

### ISSUE THREAD

**Issue by rclabo** [0xFireball/YetAnotherShrinker#2]
Using your project in VS2017 I was able to get hot replacement working with Chrome.  Thanks!   But I was unable to get it to work with IE 11.  I'm guessing I need to polyfill something that IE is missing.  Any idea what that might be or any idea on how I can get hot replace working in IE 11?  

As and aside, I tried to post this as a comment to your blog article but got the following error:
Error 403 We're sorry, but we could not fulfill your request for /wp-comments-post.php?for=jetpack on this server. You do not have permission to access this server. Data may not be posted from offsite forms.
Your technical support key is: a29e-4f86-cd36-1abb
You can use this key to fix this problem yourself.

No worries on about not being able to post a blog comment, just thought I'd mention it so you were aware.  But if you could offer a suggestion for getting hot replacement working in IE 11 that would be awesome.  
Thanks for a great article and project!

-Ron

**Comment by 0xFireball** [comment]
Hello @rclabo!

Thanks for your note about the blog, it has been addressed.

Unfortunately, I have no idea what's missing in IE11 😛, you may want to ask the Webpack guys, because YetAnotherShrinker uses Webpack's hot module replacement.

Thanks!
